/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as interfacesSol from "./Interfaces.sol";
export { DappadSaleFactoryONFTHolders__factory } from "./DappadSaleFactoryONFTHolders__factory";
export { DappadSaleONFTHolders__factory } from "./DappadSaleONFTHolders__factory";
