/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IDappadStakeController } from "./IDappadStakeController";
export type { IERC20Extented } from "./IERC20Extented";
export type { IERC721Extented } from "./IERC721Extented";
