/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { DappadSale__factory } from "./DappadSale__factory";
export { IERC20Extented__factory } from "./IERC20Extented__factory";
