/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as dappGateOftSol from "./DappGateOFT.sol";
export type { dappGateOftSol };
import type * as ierc201Sol from "./IERC201.sol";
export type { ierc201Sol };
import type * as draftIerc6093Sol from "./draft-IERC6093.sol";
export type { draftIerc6093Sol };
export type { ERC165 } from "./ERC165";
export type { ERC20 } from "./ERC20";
export type { IERC165 } from "./IERC165";
export type { IERC20 } from "./IERC20";
export type { IERC20Metadata } from "./IERC20Metadata";
export type { ILayerZeroEndpoint } from "./ILayerZeroEndpoint";
export type { ILayerZeroReceiver } from "./ILayerZeroReceiver";
export type { ILayerZeroUserApplicationConfig } from "./ILayerZeroUserApplicationConfig";
export type { IOFT } from "./IOFT";
export type { IOFTCore } from "./IOFTCore";
export type { LzApp } from "./LzApp";
export type { NonblockingLzApp } from "./NonblockingLzApp";
export type { OFT } from "./OFT";
export type { OFTCore } from "./OFTCore";
export type { Ownable } from "./Ownable";
