/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace IDappadSale {
  export type SaleDetailsStruct = {
    registerStart: BigNumberish;
    registerEnd: BigNumberish;
    registerTokenAmount: BigNumberish;
    saleStart: BigNumberish;
    saleEnd: BigNumberish;
    saleTokenPrice: BigNumberish;
    maxInvestmentAmount: BigNumberish;
    projectOwnerFeePercentage: BigNumberish;
    registerTokenEnabled: boolean;
    salePaused: boolean;
    saleName: string;
  };

  export type SaleDetailsStructOutput = [
    registerStart: bigint,
    registerEnd: bigint,
    registerTokenAmount: bigint,
    saleStart: bigint,
    saleEnd: bigint,
    saleTokenPrice: bigint,
    maxInvestmentAmount: bigint,
    projectOwnerFeePercentage: bigint,
    registerTokenEnabled: boolean,
    salePaused: boolean,
    saleName: string
  ] & {
    registerStart: bigint;
    registerEnd: bigint;
    registerTokenAmount: bigint;
    saleStart: bigint;
    saleEnd: bigint;
    saleTokenPrice: bigint;
    maxInvestmentAmount: bigint;
    projectOwnerFeePercentage: bigint;
    registerTokenEnabled: boolean;
    salePaused: boolean;
    saleName: string;
  };

  export type SaleFcfsDetailsStruct = {
    fcfsSaleDuration: BigNumberish;
    fcfsSaleMultiplier: BigNumberish;
  };

  export type SaleFcfsDetailsStructOutput = [
    fcfsSaleDuration: bigint,
    fcfsSaleMultiplier: bigint
  ] & { fcfsSaleDuration: bigint; fcfsSaleMultiplier: bigint };

  export type SaleRefundDetailsStruct = {
    refundDuration: BigNumberish;
    refundEnabled: boolean;
  };

  export type SaleRefundDetailsStructOutput = [
    refundDuration: bigint,
    refundEnabled: boolean
  ] & { refundDuration: bigint; refundEnabled: boolean };

  export type SaleTicketDetailsStruct = {
    ticketPrice: BigNumberish;
    ticketMerkleRoot: BytesLike;
  };

  export type SaleTicketDetailsStructOutput = [
    ticketPrice: bigint,
    ticketMerkleRoot: string
  ] & { ticketPrice: bigint; ticketMerkleRoot: string };

  export type SaleAddressesStruct = {
    saleTokenAddress: AddressLike;
    registerTokenAddress: AddressLike;
    investmentTokenAddress: AddressLike;
    factoryContractAddress: AddressLike;
    nftContractAddress: AddressLike;
    stakeControllerContractAddress: AddressLike;
    vestingContractAddress: AddressLike;
    ownerAddress: AddressLike;
    adminAddress: AddressLike;
    launchpadFeeAddress: AddressLike;
    projectOwnerFeeAddress: AddressLike;
  };

  export type SaleAddressesStructOutput = [
    saleTokenAddress: string,
    registerTokenAddress: string,
    investmentTokenAddress: string,
    factoryContractAddress: string,
    nftContractAddress: string,
    stakeControllerContractAddress: string,
    vestingContractAddress: string,
    ownerAddress: string,
    adminAddress: string,
    launchpadFeeAddress: string,
    projectOwnerFeeAddress: string
  ] & {
    saleTokenAddress: string;
    registerTokenAddress: string;
    investmentTokenAddress: string;
    factoryContractAddress: string;
    nftContractAddress: string;
    stakeControllerContractAddress: string;
    vestingContractAddress: string;
    ownerAddress: string;
    adminAddress: string;
    launchpadFeeAddress: string;
    projectOwnerFeeAddress: string;
  };

  export type SaleStruct = {
    saleDetails: IDappadSale.SaleDetailsStruct;
    fcfsDetails: IDappadSale.SaleFcfsDetailsStruct;
    refundDetails: IDappadSale.SaleRefundDetailsStruct;
    ticketDetails: IDappadSale.SaleTicketDetailsStruct;
    saleAddresses: IDappadSale.SaleAddressesStruct;
  };

  export type SaleStructOutput = [
    saleDetails: IDappadSale.SaleDetailsStructOutput,
    fcfsDetails: IDappadSale.SaleFcfsDetailsStructOutput,
    refundDetails: IDappadSale.SaleRefundDetailsStructOutput,
    ticketDetails: IDappadSale.SaleTicketDetailsStructOutput,
    saleAddresses: IDappadSale.SaleAddressesStructOutput
  ] & {
    saleDetails: IDappadSale.SaleDetailsStructOutput;
    fcfsDetails: IDappadSale.SaleFcfsDetailsStructOutput;
    refundDetails: IDappadSale.SaleRefundDetailsStructOutput;
    ticketDetails: IDappadSale.SaleTicketDetailsStructOutput;
    saleAddresses: IDappadSale.SaleAddressesStructOutput;
  };

  export type SaleTierDetailsStruct = {
    minInvestmentAmount: BigNumberish;
    maxInvestmentAmount: BigNumberish;
    tierMaxInvestmentAmount: BigNumberish;
    ticketAmount: BigNumberish;
    whitelistMerkleRoot: BytesLike;
    totalInvestmentAmount: BigNumberish;
    totalParticipants: BigNumberish;
  };

  export type SaleTierDetailsStructOutput = [
    minInvestmentAmount: bigint,
    maxInvestmentAmount: bigint,
    tierMaxInvestmentAmount: bigint,
    ticketAmount: bigint,
    whitelistMerkleRoot: string,
    totalInvestmentAmount: bigint,
    totalParticipants: bigint
  ] & {
    minInvestmentAmount: bigint;
    maxInvestmentAmount: bigint;
    tierMaxInvestmentAmount: bigint;
    ticketAmount: bigint;
    whitelistMerkleRoot: string;
    totalInvestmentAmount: bigint;
    totalParticipants: bigint;
  };

  export type SaleParamsStruct = {
    sale: IDappadSale.SaleStruct;
    tierDetails: IDappadSale.SaleTierDetailsStruct[];
  };

  export type SaleParamsStructOutput = [
    sale: IDappadSale.SaleStructOutput,
    tierDetails: IDappadSale.SaleTierDetailsStructOutput[]
  ] & {
    sale: IDappadSale.SaleStructOutput;
    tierDetails: IDappadSale.SaleTierDetailsStructOutput[];
  };
}

export interface DappadSaleInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "ADMIN"
      | "DEFAULT_ADMIN_ROLE"
      | "OWNER"
      | "checkTicketEligibility"
      | "checkWhitelistEligibility"
      | "completeSale"
      | "emergencyOnly"
      | "getAllTierDetails"
      | "getFactoryContractAddress"
      | "getIsSaleActive"
      | "getRefundEnabled"
      | "getRoleAdmin"
      | "getSaleEndDate"
      | "getSaleTokenAddress"
      | "getSaleTokenPrice"
      | "getStakeControllerContractAddress"
      | "getTierCount"
      | "getTierDetailsByIndex"
      | "getUserInvestmentAmount"
      | "getUserRefunded"
      | "grantRole"
      | "hasRole"
      | "investmentAmounts"
      | "investmentToken"
      | "joinFcfsSale"
      | "joinSale"
      | "refund"
      | "refunded"
      | "registerDetails"
      | "registerSale"
      | "registerToken"
      | "renounceRole"
      | "revokeRole"
      | "sale"
      | "saleStatistics"
      | "setRefundDetails"
      | "setSaleAddresses"
      | "setSaleDetails"
      | "setSaleFcfsDetails"
      | "setSalePaused"
      | "setStakeControllerContract"
      | "setTicketDetails"
      | "setTierDetails"
      | "setTierDetailsBatch"
      | "setVestingContract"
      | "stakeControllerContract"
      | "supportsInterface"
      | "tierDetails"
      | "vestingContract"
      | "withdrawRegisterToken"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
      | "SaleAddressesUpdated"
      | "SaleCompleted"
      | "SaleDetailsUpdated"
      | "SaleFcfsDetailsUpdated"
      | "SalePausedUpdated"
      | "SaleRefundDetailsUpdated"
      | "SaleTicketDetailsUpdated"
      | "SaleTierDetailsBatchUpdated"
      | "SaleTierDetailsUpdated"
      | "StakeControllerContractUpdated"
      | "UserJoinedFcfsSale"
      | "UserJoinedSale"
      | "UserRefundedSale"
      | "UserRegisteredSale"
      | "VestingContractUpdated"
  ): EventFragment;

  encodeFunctionData(functionFragment: "ADMIN", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "OWNER", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "checkTicketEligibility",
    values: [AddressLike, BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "checkWhitelistEligibility",
    values: [AddressLike, BigNumberish, BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "completeSale",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyOnly",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAllTierDetails",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getFactoryContractAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getIsSaleActive",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRefundEnabled",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getSaleEndDate",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getSaleTokenAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getSaleTokenPrice",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getStakeControllerContractAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTierCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTierDetailsByIndex",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserInvestmentAmount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserRefunded",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "investmentAmounts",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "investmentToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "joinFcfsSale",
    values: [BigNumberish, BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "joinSale",
    values: [BigNumberish, BytesLike[], BytesLike[]]
  ): string;
  encodeFunctionData(functionFragment: "refund", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "refunded",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "registerDetails",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "registerSale",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "registerToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "sale", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "saleStatistics",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setRefundDetails",
    values: [IDappadSale.SaleRefundDetailsStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "setSaleAddresses",
    values: [IDappadSale.SaleAddressesStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "setSaleDetails",
    values: [IDappadSale.SaleDetailsStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "setSaleFcfsDetails",
    values: [IDappadSale.SaleFcfsDetailsStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "setSalePaused",
    values: [boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setStakeControllerContract",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setTicketDetails",
    values: [IDappadSale.SaleTicketDetailsStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "setTierDetails",
    values: [BigNumberish, IDappadSale.SaleTierDetailsStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "setTierDetailsBatch",
    values: [IDappadSale.SaleTierDetailsStruct[]]
  ): string;
  encodeFunctionData(
    functionFragment: "setVestingContract",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "stakeControllerContract",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "tierDetails",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "vestingContract",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawRegisterToken",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "ADMIN", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "OWNER", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "checkTicketEligibility",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkWhitelistEligibility",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "completeSale",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyOnly",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllTierDetails",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getFactoryContractAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getIsSaleActive",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRefundEnabled",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSaleEndDate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSaleTokenAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSaleTokenPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getStakeControllerContractAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTierCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTierDetailsByIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserInvestmentAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserRefunded",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "investmentAmounts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "investmentToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "joinFcfsSale",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "joinSale", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "refund", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "refunded", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerDetails",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerSale",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "sale", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "saleStatistics",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setRefundDetails",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setSaleAddresses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setSaleDetails",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setSaleFcfsDetails",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setSalePaused",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setStakeControllerContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTicketDetails",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTierDetails",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTierDetailsBatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setVestingContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "stakeControllerContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tierDetails",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "vestingContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawRegisterToken",
    data: BytesLike
  ): Result;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SaleAddressesUpdatedEvent {
  export type InputTuple = [newSaleAddresses: IDappadSale.SaleAddressesStruct];
  export type OutputTuple = [
    newSaleAddresses: IDappadSale.SaleAddressesStructOutput
  ];
  export interface OutputObject {
    newSaleAddresses: IDappadSale.SaleAddressesStructOutput;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SaleCompletedEvent {
  export type InputTuple = [
    projectOwnerFeeAddress: AddressLike,
    projectOwnerFeeAmount: BigNumberish,
    launchpadFeeAddress: AddressLike,
    launchpadFeeAmount: BigNumberish,
    completedTime: BigNumberish
  ];
  export type OutputTuple = [
    projectOwnerFeeAddress: string,
    projectOwnerFeeAmount: bigint,
    launchpadFeeAddress: string,
    launchpadFeeAmount: bigint,
    completedTime: bigint
  ];
  export interface OutputObject {
    projectOwnerFeeAddress: string;
    projectOwnerFeeAmount: bigint;
    launchpadFeeAddress: string;
    launchpadFeeAmount: bigint;
    completedTime: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SaleDetailsUpdatedEvent {
  export type InputTuple = [newSaleDetails: IDappadSale.SaleDetailsStruct];
  export type OutputTuple = [
    newSaleDetails: IDappadSale.SaleDetailsStructOutput
  ];
  export interface OutputObject {
    newSaleDetails: IDappadSale.SaleDetailsStructOutput;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SaleFcfsDetailsUpdatedEvent {
  export type InputTuple = [newFcfsDetails: IDappadSale.SaleFcfsDetailsStruct];
  export type OutputTuple = [
    newFcfsDetails: IDappadSale.SaleFcfsDetailsStructOutput
  ];
  export interface OutputObject {
    newFcfsDetails: IDappadSale.SaleFcfsDetailsStructOutput;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SalePausedUpdatedEvent {
  export type InputTuple = [salePaused: boolean];
  export type OutputTuple = [salePaused: boolean];
  export interface OutputObject {
    salePaused: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SaleRefundDetailsUpdatedEvent {
  export type InputTuple = [
    newRefundDetails: IDappadSale.SaleRefundDetailsStruct
  ];
  export type OutputTuple = [
    newRefundDetails: IDappadSale.SaleRefundDetailsStructOutput
  ];
  export interface OutputObject {
    newRefundDetails: IDappadSale.SaleRefundDetailsStructOutput;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SaleTicketDetailsUpdatedEvent {
  export type InputTuple = [
    newTicketDetails: IDappadSale.SaleTicketDetailsStruct
  ];
  export type OutputTuple = [
    newTicketDetails: IDappadSale.SaleTicketDetailsStructOutput
  ];
  export interface OutputObject {
    newTicketDetails: IDappadSale.SaleTicketDetailsStructOutput;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SaleTierDetailsBatchUpdatedEvent {
  export type InputTuple = [
    newTierDetails: IDappadSale.SaleTierDetailsStruct[]
  ];
  export type OutputTuple = [
    newTierDetails: IDappadSale.SaleTierDetailsStructOutput[]
  ];
  export interface OutputObject {
    newTierDetails: IDappadSale.SaleTierDetailsStructOutput[];
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SaleTierDetailsUpdatedEvent {
  export type InputTuple = [
    tierIndex: BigNumberish,
    newTierDetails: IDappadSale.SaleTierDetailsStruct
  ];
  export type OutputTuple = [
    tierIndex: bigint,
    newTierDetails: IDappadSale.SaleTierDetailsStructOutput
  ];
  export interface OutputObject {
    tierIndex: bigint;
    newTierDetails: IDappadSale.SaleTierDetailsStructOutput;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StakeControllerContractUpdatedEvent {
  export type InputTuple = [stakeControllerContractAddress: AddressLike];
  export type OutputTuple = [stakeControllerContractAddress: string];
  export interface OutputObject {
    stakeControllerContractAddress: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UserJoinedFcfsSaleEvent {
  export type InputTuple = [
    user: AddressLike,
    tierIndex: BigNumberish,
    amount: BigNumberish,
    investmentAmount: BigNumberish,
    totalInvestmentAmount: BigNumberish,
    totalParticipants: BigNumberish,
    joinedTime: BigNumberish,
    nftBalance: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    tierIndex: bigint,
    amount: bigint,
    investmentAmount: bigint,
    totalInvestmentAmount: bigint,
    totalParticipants: bigint,
    joinedTime: bigint,
    nftBalance: bigint
  ];
  export interface OutputObject {
    user: string;
    tierIndex: bigint;
    amount: bigint;
    investmentAmount: bigint;
    totalInvestmentAmount: bigint;
    totalParticipants: bigint;
    joinedTime: bigint;
    nftBalance: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UserJoinedSaleEvent {
  export type InputTuple = [
    user: AddressLike,
    tierIndex: BigNumberish,
    amount: BigNumberish,
    investmentAmount: BigNumberish,
    totalInvestmentAmount: BigNumberish,
    totalParticipants: BigNumberish,
    joinedTime: BigNumberish,
    nftBalance: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    tierIndex: bigint,
    amount: bigint,
    investmentAmount: bigint,
    totalInvestmentAmount: bigint,
    totalParticipants: bigint,
    joinedTime: bigint,
    nftBalance: bigint
  ];
  export interface OutputObject {
    user: string;
    tierIndex: bigint;
    amount: bigint;
    investmentAmount: bigint;
    totalInvestmentAmount: bigint;
    totalParticipants: bigint;
    joinedTime: bigint;
    nftBalance: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UserRefundedSaleEvent {
  export type InputTuple = [
    user: AddressLike,
    userTierIndex: BigNumberish,
    investmentAmount: BigNumberish,
    totalInvestmentAmount: BigNumberish,
    refundedTime: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    userTierIndex: bigint,
    investmentAmount: bigint,
    totalInvestmentAmount: bigint,
    refundedTime: bigint
  ];
  export interface OutputObject {
    user: string;
    userTierIndex: bigint;
    investmentAmount: bigint;
    totalInvestmentAmount: bigint;
    refundedTime: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UserRegisteredSaleEvent {
  export type InputTuple = [
    user: AddressLike,
    tierIndex: BigNumberish,
    registerTime: BigNumberish,
    totalRegisters: BigNumberish,
    totalRegisterTokenAmountLeft: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    tierIndex: bigint,
    registerTime: bigint,
    totalRegisters: bigint,
    totalRegisterTokenAmountLeft: bigint
  ];
  export interface OutputObject {
    user: string;
    tierIndex: bigint;
    registerTime: bigint;
    totalRegisters: bigint;
    totalRegisterTokenAmountLeft: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VestingContractUpdatedEvent {
  export type InputTuple = [vestingContractAddress: AddressLike];
  export type OutputTuple = [vestingContractAddress: string];
  export interface OutputObject {
    vestingContractAddress: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface DappadSale extends BaseContract {
  connect(runner?: ContractRunner | null): DappadSale;
  waitForDeployment(): Promise<this>;

  interface: DappadSaleInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  ADMIN: TypedContractMethod<[], [string], "view">;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  OWNER: TypedContractMethod<[], [string], "view">;

  checkTicketEligibility: TypedContractMethod<
    [userAddress: AddressLike, proof: BytesLike[]],
    [boolean],
    "view"
  >;

  checkWhitelistEligibility: TypedContractMethod<
    [userAddress: AddressLike, userTierIndex: BigNumberish, proof: BytesLike[]],
    [boolean],
    "view"
  >;

  completeSale: TypedContractMethod<[], [boolean], "nonpayable">;

  emergencyOnly: TypedContractMethod<[], [boolean], "nonpayable">;

  getAllTierDetails: TypedContractMethod<
    [],
    [IDappadSale.SaleTierDetailsStructOutput[]],
    "view"
  >;

  getFactoryContractAddress: TypedContractMethod<[], [string], "view">;

  getIsSaleActive: TypedContractMethod<[], [boolean], "view">;

  getRefundEnabled: TypedContractMethod<[], [boolean], "view">;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  getSaleEndDate: TypedContractMethod<[], [bigint], "view">;

  getSaleTokenAddress: TypedContractMethod<[], [string], "view">;

  getSaleTokenPrice: TypedContractMethod<[], [bigint], "view">;

  getStakeControllerContractAddress: TypedContractMethod<[], [string], "view">;

  getTierCount: TypedContractMethod<[], [bigint], "view">;

  getTierDetailsByIndex: TypedContractMethod<
    [tierIndex: BigNumberish],
    [IDappadSale.SaleTierDetailsStructOutput],
    "view"
  >;

  getUserInvestmentAmount: TypedContractMethod<
    [userAddress: AddressLike],
    [bigint],
    "view"
  >;

  getUserRefunded: TypedContractMethod<
    [userAddress: AddressLike],
    [boolean],
    "view"
  >;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  investmentAmounts: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  investmentToken: TypedContractMethod<[], [string], "view">;

  joinFcfsSale: TypedContractMethod<
    [amount: BigNumberish, whitelistProof: BytesLike[]],
    [boolean],
    "nonpayable"
  >;

  joinSale: TypedContractMethod<
    [
      amount: BigNumberish,
      whitelistProof: BytesLike[],
      ticketProof: BytesLike[]
    ],
    [boolean],
    "nonpayable"
  >;

  refund: TypedContractMethod<[], [boolean], "nonpayable">;

  refunded: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  registerDetails: TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, boolean] & {
        registerTokenAmount: bigint;
        tierIndex: bigint;
        registered: boolean;
      }
    ],
    "view"
  >;

  registerSale: TypedContractMethod<[], [boolean], "nonpayable">;

  registerToken: TypedContractMethod<[], [string], "view">;

  renounceRole: TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  sale: TypedContractMethod<
    [],
    [
      [
        IDappadSale.SaleDetailsStructOutput,
        IDappadSale.SaleFcfsDetailsStructOutput,
        IDappadSale.SaleRefundDetailsStructOutput,
        IDappadSale.SaleTicketDetailsStructOutput,
        IDappadSale.SaleAddressesStructOutput
      ] & {
        saleDetails: IDappadSale.SaleDetailsStructOutput;
        fcfsDetails: IDappadSale.SaleFcfsDetailsStructOutput;
        refundDetails: IDappadSale.SaleRefundDetailsStructOutput;
        ticketDetails: IDappadSale.SaleTicketDetailsStructOutput;
        saleAddresses: IDappadSale.SaleAddressesStructOutput;
      }
    ],
    "view"
  >;

  saleStatistics: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint, bigint] & {
        totalInvestmentAmount: bigint;
        totalSaleTokenAmount: bigint;
        totalParticipants: bigint;
        totalRegisters: bigint;
        totalRegisterTokenAmountLeft: bigint;
      }
    ],
    "view"
  >;

  setRefundDetails: TypedContractMethod<
    [newRefundDetails: IDappadSale.SaleRefundDetailsStruct],
    [boolean],
    "nonpayable"
  >;

  setSaleAddresses: TypedContractMethod<
    [newSaleAddresses: IDappadSale.SaleAddressesStruct],
    [boolean],
    "nonpayable"
  >;

  setSaleDetails: TypedContractMethod<
    [newSaleDetails: IDappadSale.SaleDetailsStruct],
    [boolean],
    "nonpayable"
  >;

  setSaleFcfsDetails: TypedContractMethod<
    [newFcfsDetails: IDappadSale.SaleFcfsDetailsStruct],
    [boolean],
    "nonpayable"
  >;

  setSalePaused: TypedContractMethod<
    [salePaused: boolean],
    [boolean],
    "nonpayable"
  >;

  setStakeControllerContract: TypedContractMethod<
    [stakeControllerContractAddress: AddressLike],
    [boolean],
    "nonpayable"
  >;

  setTicketDetails: TypedContractMethod<
    [newTicketDetails: IDappadSale.SaleTicketDetailsStruct],
    [boolean],
    "nonpayable"
  >;

  setTierDetails: TypedContractMethod<
    [
      tierIndex: BigNumberish,
      newTierDetails: IDappadSale.SaleTierDetailsStruct
    ],
    [boolean],
    "nonpayable"
  >;

  setTierDetailsBatch: TypedContractMethod<
    [newTierDetails: IDappadSale.SaleTierDetailsStruct[]],
    [boolean],
    "nonpayable"
  >;

  setVestingContract: TypedContractMethod<
    [vestingContractAddress: AddressLike],
    [boolean],
    "nonpayable"
  >;

  stakeControllerContract: TypedContractMethod<[], [string], "view">;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  tierDetails: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, string, bigint, bigint] & {
        minInvestmentAmount: bigint;
        maxInvestmentAmount: bigint;
        tierMaxInvestmentAmount: bigint;
        ticketAmount: bigint;
        whitelistMerkleRoot: string;
        totalInvestmentAmount: bigint;
        totalParticipants: bigint;
      }
    ],
    "view"
  >;

  vestingContract: TypedContractMethod<[], [string], "view">;

  withdrawRegisterToken: TypedContractMethod<[], [boolean], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "ADMIN"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "OWNER"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "checkTicketEligibility"
  ): TypedContractMethod<
    [userAddress: AddressLike, proof: BytesLike[]],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "checkWhitelistEligibility"
  ): TypedContractMethod<
    [userAddress: AddressLike, userTierIndex: BigNumberish, proof: BytesLike[]],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "completeSale"
  ): TypedContractMethod<[], [boolean], "nonpayable">;
  getFunction(
    nameOrSignature: "emergencyOnly"
  ): TypedContractMethod<[], [boolean], "nonpayable">;
  getFunction(
    nameOrSignature: "getAllTierDetails"
  ): TypedContractMethod<
    [],
    [IDappadSale.SaleTierDetailsStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getFactoryContractAddress"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getIsSaleActive"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "getRefundEnabled"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "getSaleEndDate"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getSaleTokenAddress"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getSaleTokenPrice"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getStakeControllerContractAddress"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getTierCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getTierDetailsByIndex"
  ): TypedContractMethod<
    [tierIndex: BigNumberish],
    [IDappadSale.SaleTierDetailsStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserInvestmentAmount"
  ): TypedContractMethod<[userAddress: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getUserRefunded"
  ): TypedContractMethod<[userAddress: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "investmentAmounts"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "investmentToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "joinFcfsSale"
  ): TypedContractMethod<
    [amount: BigNumberish, whitelistProof: BytesLike[]],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "joinSale"
  ): TypedContractMethod<
    [
      amount: BigNumberish,
      whitelistProof: BytesLike[],
      ticketProof: BytesLike[]
    ],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "refund"
  ): TypedContractMethod<[], [boolean], "nonpayable">;
  getFunction(
    nameOrSignature: "refunded"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "registerDetails"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, boolean] & {
        registerTokenAmount: bigint;
        tierIndex: bigint;
        registered: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "registerSale"
  ): TypedContractMethod<[], [boolean], "nonpayable">;
  getFunction(
    nameOrSignature: "registerToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "sale"
  ): TypedContractMethod<
    [],
    [
      [
        IDappadSale.SaleDetailsStructOutput,
        IDappadSale.SaleFcfsDetailsStructOutput,
        IDappadSale.SaleRefundDetailsStructOutput,
        IDappadSale.SaleTicketDetailsStructOutput,
        IDappadSale.SaleAddressesStructOutput
      ] & {
        saleDetails: IDappadSale.SaleDetailsStructOutput;
        fcfsDetails: IDappadSale.SaleFcfsDetailsStructOutput;
        refundDetails: IDappadSale.SaleRefundDetailsStructOutput;
        ticketDetails: IDappadSale.SaleTicketDetailsStructOutput;
        saleAddresses: IDappadSale.SaleAddressesStructOutput;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "saleStatistics"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint, bigint] & {
        totalInvestmentAmount: bigint;
        totalSaleTokenAmount: bigint;
        totalParticipants: bigint;
        totalRegisters: bigint;
        totalRegisterTokenAmountLeft: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "setRefundDetails"
  ): TypedContractMethod<
    [newRefundDetails: IDappadSale.SaleRefundDetailsStruct],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setSaleAddresses"
  ): TypedContractMethod<
    [newSaleAddresses: IDappadSale.SaleAddressesStruct],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setSaleDetails"
  ): TypedContractMethod<
    [newSaleDetails: IDappadSale.SaleDetailsStruct],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setSaleFcfsDetails"
  ): TypedContractMethod<
    [newFcfsDetails: IDappadSale.SaleFcfsDetailsStruct],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setSalePaused"
  ): TypedContractMethod<[salePaused: boolean], [boolean], "nonpayable">;
  getFunction(
    nameOrSignature: "setStakeControllerContract"
  ): TypedContractMethod<
    [stakeControllerContractAddress: AddressLike],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setTicketDetails"
  ): TypedContractMethod<
    [newTicketDetails: IDappadSale.SaleTicketDetailsStruct],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setTierDetails"
  ): TypedContractMethod<
    [
      tierIndex: BigNumberish,
      newTierDetails: IDappadSale.SaleTierDetailsStruct
    ],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setTierDetailsBatch"
  ): TypedContractMethod<
    [newTierDetails: IDappadSale.SaleTierDetailsStruct[]],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setVestingContract"
  ): TypedContractMethod<
    [vestingContractAddress: AddressLike],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "stakeControllerContract"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "tierDetails"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, string, bigint, bigint] & {
        minInvestmentAmount: bigint;
        maxInvestmentAmount: bigint;
        tierMaxInvestmentAmount: bigint;
        ticketAmount: bigint;
        whitelistMerkleRoot: string;
        totalInvestmentAmount: bigint;
        totalParticipants: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "vestingContract"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "withdrawRegisterToken"
  ): TypedContractMethod<[], [boolean], "nonpayable">;

  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "SaleAddressesUpdated"
  ): TypedContractEvent<
    SaleAddressesUpdatedEvent.InputTuple,
    SaleAddressesUpdatedEvent.OutputTuple,
    SaleAddressesUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "SaleCompleted"
  ): TypedContractEvent<
    SaleCompletedEvent.InputTuple,
    SaleCompletedEvent.OutputTuple,
    SaleCompletedEvent.OutputObject
  >;
  getEvent(
    key: "SaleDetailsUpdated"
  ): TypedContractEvent<
    SaleDetailsUpdatedEvent.InputTuple,
    SaleDetailsUpdatedEvent.OutputTuple,
    SaleDetailsUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "SaleFcfsDetailsUpdated"
  ): TypedContractEvent<
    SaleFcfsDetailsUpdatedEvent.InputTuple,
    SaleFcfsDetailsUpdatedEvent.OutputTuple,
    SaleFcfsDetailsUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "SalePausedUpdated"
  ): TypedContractEvent<
    SalePausedUpdatedEvent.InputTuple,
    SalePausedUpdatedEvent.OutputTuple,
    SalePausedUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "SaleRefundDetailsUpdated"
  ): TypedContractEvent<
    SaleRefundDetailsUpdatedEvent.InputTuple,
    SaleRefundDetailsUpdatedEvent.OutputTuple,
    SaleRefundDetailsUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "SaleTicketDetailsUpdated"
  ): TypedContractEvent<
    SaleTicketDetailsUpdatedEvent.InputTuple,
    SaleTicketDetailsUpdatedEvent.OutputTuple,
    SaleTicketDetailsUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "SaleTierDetailsBatchUpdated"
  ): TypedContractEvent<
    SaleTierDetailsBatchUpdatedEvent.InputTuple,
    SaleTierDetailsBatchUpdatedEvent.OutputTuple,
    SaleTierDetailsBatchUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "SaleTierDetailsUpdated"
  ): TypedContractEvent<
    SaleTierDetailsUpdatedEvent.InputTuple,
    SaleTierDetailsUpdatedEvent.OutputTuple,
    SaleTierDetailsUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "StakeControllerContractUpdated"
  ): TypedContractEvent<
    StakeControllerContractUpdatedEvent.InputTuple,
    StakeControllerContractUpdatedEvent.OutputTuple,
    StakeControllerContractUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "UserJoinedFcfsSale"
  ): TypedContractEvent<
    UserJoinedFcfsSaleEvent.InputTuple,
    UserJoinedFcfsSaleEvent.OutputTuple,
    UserJoinedFcfsSaleEvent.OutputObject
  >;
  getEvent(
    key: "UserJoinedSale"
  ): TypedContractEvent<
    UserJoinedSaleEvent.InputTuple,
    UserJoinedSaleEvent.OutputTuple,
    UserJoinedSaleEvent.OutputObject
  >;
  getEvent(
    key: "UserRefundedSale"
  ): TypedContractEvent<
    UserRefundedSaleEvent.InputTuple,
    UserRefundedSaleEvent.OutputTuple,
    UserRefundedSaleEvent.OutputObject
  >;
  getEvent(
    key: "UserRegisteredSale"
  ): TypedContractEvent<
    UserRegisteredSaleEvent.InputTuple,
    UserRegisteredSaleEvent.OutputTuple,
    UserRegisteredSaleEvent.OutputObject
  >;
  getEvent(
    key: "VestingContractUpdated"
  ): TypedContractEvent<
    VestingContractUpdatedEvent.InputTuple,
    VestingContractUpdatedEvent.OutputTuple,
    VestingContractUpdatedEvent.OutputObject
  >;

  filters: {
    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;

    "SaleAddressesUpdated(tuple)": TypedContractEvent<
      SaleAddressesUpdatedEvent.InputTuple,
      SaleAddressesUpdatedEvent.OutputTuple,
      SaleAddressesUpdatedEvent.OutputObject
    >;
    SaleAddressesUpdated: TypedContractEvent<
      SaleAddressesUpdatedEvent.InputTuple,
      SaleAddressesUpdatedEvent.OutputTuple,
      SaleAddressesUpdatedEvent.OutputObject
    >;

    "SaleCompleted(address,uint256,address,uint256,uint256)": TypedContractEvent<
      SaleCompletedEvent.InputTuple,
      SaleCompletedEvent.OutputTuple,
      SaleCompletedEvent.OutputObject
    >;
    SaleCompleted: TypedContractEvent<
      SaleCompletedEvent.InputTuple,
      SaleCompletedEvent.OutputTuple,
      SaleCompletedEvent.OutputObject
    >;

    "SaleDetailsUpdated(tuple)": TypedContractEvent<
      SaleDetailsUpdatedEvent.InputTuple,
      SaleDetailsUpdatedEvent.OutputTuple,
      SaleDetailsUpdatedEvent.OutputObject
    >;
    SaleDetailsUpdated: TypedContractEvent<
      SaleDetailsUpdatedEvent.InputTuple,
      SaleDetailsUpdatedEvent.OutputTuple,
      SaleDetailsUpdatedEvent.OutputObject
    >;

    "SaleFcfsDetailsUpdated(tuple)": TypedContractEvent<
      SaleFcfsDetailsUpdatedEvent.InputTuple,
      SaleFcfsDetailsUpdatedEvent.OutputTuple,
      SaleFcfsDetailsUpdatedEvent.OutputObject
    >;
    SaleFcfsDetailsUpdated: TypedContractEvent<
      SaleFcfsDetailsUpdatedEvent.InputTuple,
      SaleFcfsDetailsUpdatedEvent.OutputTuple,
      SaleFcfsDetailsUpdatedEvent.OutputObject
    >;

    "SalePausedUpdated(bool)": TypedContractEvent<
      SalePausedUpdatedEvent.InputTuple,
      SalePausedUpdatedEvent.OutputTuple,
      SalePausedUpdatedEvent.OutputObject
    >;
    SalePausedUpdated: TypedContractEvent<
      SalePausedUpdatedEvent.InputTuple,
      SalePausedUpdatedEvent.OutputTuple,
      SalePausedUpdatedEvent.OutputObject
    >;

    "SaleRefundDetailsUpdated(tuple)": TypedContractEvent<
      SaleRefundDetailsUpdatedEvent.InputTuple,
      SaleRefundDetailsUpdatedEvent.OutputTuple,
      SaleRefundDetailsUpdatedEvent.OutputObject
    >;
    SaleRefundDetailsUpdated: TypedContractEvent<
      SaleRefundDetailsUpdatedEvent.InputTuple,
      SaleRefundDetailsUpdatedEvent.OutputTuple,
      SaleRefundDetailsUpdatedEvent.OutputObject
    >;

    "SaleTicketDetailsUpdated(tuple)": TypedContractEvent<
      SaleTicketDetailsUpdatedEvent.InputTuple,
      SaleTicketDetailsUpdatedEvent.OutputTuple,
      SaleTicketDetailsUpdatedEvent.OutputObject
    >;
    SaleTicketDetailsUpdated: TypedContractEvent<
      SaleTicketDetailsUpdatedEvent.InputTuple,
      SaleTicketDetailsUpdatedEvent.OutputTuple,
      SaleTicketDetailsUpdatedEvent.OutputObject
    >;

    "SaleTierDetailsBatchUpdated(tuple[])": TypedContractEvent<
      SaleTierDetailsBatchUpdatedEvent.InputTuple,
      SaleTierDetailsBatchUpdatedEvent.OutputTuple,
      SaleTierDetailsBatchUpdatedEvent.OutputObject
    >;
    SaleTierDetailsBatchUpdated: TypedContractEvent<
      SaleTierDetailsBatchUpdatedEvent.InputTuple,
      SaleTierDetailsBatchUpdatedEvent.OutputTuple,
      SaleTierDetailsBatchUpdatedEvent.OutputObject
    >;

    "SaleTierDetailsUpdated(uint256,tuple)": TypedContractEvent<
      SaleTierDetailsUpdatedEvent.InputTuple,
      SaleTierDetailsUpdatedEvent.OutputTuple,
      SaleTierDetailsUpdatedEvent.OutputObject
    >;
    SaleTierDetailsUpdated: TypedContractEvent<
      SaleTierDetailsUpdatedEvent.InputTuple,
      SaleTierDetailsUpdatedEvent.OutputTuple,
      SaleTierDetailsUpdatedEvent.OutputObject
    >;

    "StakeControllerContractUpdated(address)": TypedContractEvent<
      StakeControllerContractUpdatedEvent.InputTuple,
      StakeControllerContractUpdatedEvent.OutputTuple,
      StakeControllerContractUpdatedEvent.OutputObject
    >;
    StakeControllerContractUpdated: TypedContractEvent<
      StakeControllerContractUpdatedEvent.InputTuple,
      StakeControllerContractUpdatedEvent.OutputTuple,
      StakeControllerContractUpdatedEvent.OutputObject
    >;

    "UserJoinedFcfsSale(address,uint256,uint256,uint256,uint256,uint256,uint256,uint256)": TypedContractEvent<
      UserJoinedFcfsSaleEvent.InputTuple,
      UserJoinedFcfsSaleEvent.OutputTuple,
      UserJoinedFcfsSaleEvent.OutputObject
    >;
    UserJoinedFcfsSale: TypedContractEvent<
      UserJoinedFcfsSaleEvent.InputTuple,
      UserJoinedFcfsSaleEvent.OutputTuple,
      UserJoinedFcfsSaleEvent.OutputObject
    >;

    "UserJoinedSale(address,uint256,uint256,uint256,uint256,uint256,uint256,uint256)": TypedContractEvent<
      UserJoinedSaleEvent.InputTuple,
      UserJoinedSaleEvent.OutputTuple,
      UserJoinedSaleEvent.OutputObject
    >;
    UserJoinedSale: TypedContractEvent<
      UserJoinedSaleEvent.InputTuple,
      UserJoinedSaleEvent.OutputTuple,
      UserJoinedSaleEvent.OutputObject
    >;

    "UserRefundedSale(address,uint256,uint256,uint256,uint256)": TypedContractEvent<
      UserRefundedSaleEvent.InputTuple,
      UserRefundedSaleEvent.OutputTuple,
      UserRefundedSaleEvent.OutputObject
    >;
    UserRefundedSale: TypedContractEvent<
      UserRefundedSaleEvent.InputTuple,
      UserRefundedSaleEvent.OutputTuple,
      UserRefundedSaleEvent.OutputObject
    >;

    "UserRegisteredSale(address,uint256,uint256,uint256,uint256)": TypedContractEvent<
      UserRegisteredSaleEvent.InputTuple,
      UserRegisteredSaleEvent.OutputTuple,
      UserRegisteredSaleEvent.OutputObject
    >;
    UserRegisteredSale: TypedContractEvent<
      UserRegisteredSaleEvent.InputTuple,
      UserRegisteredSaleEvent.OutputTuple,
      UserRegisteredSaleEvent.OutputObject
    >;

    "VestingContractUpdated(address)": TypedContractEvent<
      VestingContractUpdatedEvent.InputTuple,
      VestingContractUpdatedEvent.OutputTuple,
      VestingContractUpdatedEvent.OutputObject
    >;
    VestingContractUpdated: TypedContractEvent<
      VestingContractUpdatedEvent.InputTuple,
      VestingContractUpdatedEvent.OutputTuple,
      VestingContractUpdatedEvent.OutputObject
    >;
  };
}
