/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IDappadStakeController,
  IDappadStakeControllerInterface,
} from "../../../../../contracts/variants/NodeSale/Interfaces.sol/IDappadStakeController";

const _abi = [
  {
    inputs: [],
    name: "getTierCount",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "userAddress",
        type: "address",
      },
    ],
    name: "getUserTierIndex",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IDappadStakeController__factory {
  static readonly abi = _abi;
  static createInterface(): IDappadStakeControllerInterface {
    return new Interface(_abi) as IDappadStakeControllerInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IDappadStakeController {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IDappadStakeController;
  }
}
