/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as interfacesSol from "./Interfaces.sol";
export type { interfacesSol };
export type { DappadVestingFactoryONFTHolders } from "./DappadVestingFactoryONFTHolders";
export type { DappadVestingONFTHolders } from "./DappadVestingONFTHolders";
