/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../../common";

export interface IDappadVestingInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getAnyVestingClaimed"
      | "getTotalVestingAmount"
      | "getUserTotalVestingAmount"
      | "getUserUnclaimedTokenAmount"
      | "getVestingClaimed"
      | "setTotalVestingAmount"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getAnyVestingClaimed",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalVestingAmount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getUserTotalVestingAmount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserUnclaimedTokenAmount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getVestingClaimed",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setTotalVestingAmount",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "getAnyVestingClaimed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalVestingAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserTotalVestingAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserUnclaimedTokenAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getVestingClaimed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTotalVestingAmount",
    data: BytesLike
  ): Result;
}

export interface IDappadVesting extends BaseContract {
  connect(runner?: ContractRunner | null): IDappadVesting;
  waitForDeployment(): Promise<this>;

  interface: IDappadVestingInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getAnyVestingClaimed: TypedContractMethod<
    [userAddress: AddressLike],
    [boolean],
    "view"
  >;

  getTotalVestingAmount: TypedContractMethod<[], [bigint], "view">;

  getUserTotalVestingAmount: TypedContractMethod<
    [userAddress: AddressLike],
    [bigint],
    "view"
  >;

  getUserUnclaimedTokenAmount: TypedContractMethod<
    [userAddress: AddressLike],
    [bigint],
    "view"
  >;

  getVestingClaimed: TypedContractMethod<
    [userAddress: AddressLike, vestingIndex: BigNumberish],
    [boolean],
    "view"
  >;

  setTotalVestingAmount: TypedContractMethod<
    [amount: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getAnyVestingClaimed"
  ): TypedContractMethod<[userAddress: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "getTotalVestingAmount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getUserTotalVestingAmount"
  ): TypedContractMethod<[userAddress: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getUserUnclaimedTokenAmount"
  ): TypedContractMethod<[userAddress: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getVestingClaimed"
  ): TypedContractMethod<
    [userAddress: AddressLike, vestingIndex: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "setTotalVestingAmount"
  ): TypedContractMethod<[amount: BigNumberish], [boolean], "nonpayable">;

  filters: {};
}
