/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Airdrop } from "./Airdrop";
export type { AirdropB } from "./AirdropB";
export type { DappadSoulBoundToken } from "./DappadSoulBoundToken";
export type { DappadToken } from "./DappadToken";
export type { Faucet } from "./Faucet";
export type { IZkPassProofVerifier } from "./IZkPassProofVerifier";
export type { MockNFT } from "./MockNFT";
export type { MockToken } from "./MockToken";
export type { MockToken6 } from "./MockToken6";
export type { ZkPassProofVerifier } from "./ZkPassProofVerifier";
