/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { DappadPaymasterDefault } from "./DappadPaymasterDefault";
export type { DappadPaymasterGasless } from "./DappadPaymasterGasless";
