/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as interfacesSol from "./Interfaces.sol";
export type { interfacesSol };
export type { DappadSaleFactoryONFTHolders } from "./DappadSaleFactoryONFTHolders";
export type { DappadSaleONFTHolders } from "./DappadSaleONFTHolders";
