/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IDappadSale } from "./IDappadSale";
export type { IDappadStake } from "./IDappadStake";
export type { IDappadVesting } from "./IDappadVesting";
export type { IERC20Extented } from "./IERC20Extented";
export type { IERC721Extented } from "./IERC721Extented";
