/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IDappgate__factory } from "./IDappgate__factory";
export { SetContract__factory } from "./SetContract__factory";
