/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as nodeSale from "./NodeSale";
export type { nodeSale };
import type * as onftHoldersSale from "./ONFTHoldersSale";
export type { onftHoldersSale };
import type * as onftHoldersVesting from "./ONFTHoldersVesting";
export type { onftHoldersVesting };
import type * as privateSale from "./PrivateSale";
export type { privateSale };
import type * as publicSale from "./PublicSale";
export type { publicSale };
