/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as interfacesSol from "./Interfaces.sol";
export type { interfacesSol };
export type { DappadPublicSale } from "./DappadPublicSale";
export type { DappadPublicSaleFactory } from "./DappadPublicSaleFactory";
