/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  DeployContractOptions,
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "BootloaderUtilities",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.BootloaderUtilities__factory>;
    getContractFactory(
      name: "IAccountCodeStorage",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IAccountCodeStorage__factory>;
    getContractFactory(
      name: "IBootloaderUtilities",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IBootloaderUtilities__factory>;
    getContractFactory(
      name: "IBytecodeCompressor",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IBytecodeCompressor__factory>;
    getContractFactory(
      name: "IContractDeployer",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IContractDeployer__factory>;
    getContractFactory(
      name: "IEthToken",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IEthToken__factory>;
    getContractFactory(
      name: "IImmutableSimulator",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IImmutableSimulator__factory>;
    getContractFactory(
      name: "IKnownCodesStorage",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IKnownCodesStorage__factory>;
    getContractFactory(
      name: "IL1Messenger",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IL1Messenger__factory>;
    getContractFactory(
      name: "INonceHolder",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.INonceHolder__factory>;
    getContractFactory(
      name: "IPaymaster",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IPaymaster__factory>;
    getContractFactory(
      name: "IPaymasterFlow",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IPaymasterFlow__factory>;
    getContractFactory(
      name: "ISystemContext",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ISystemContext__factory>;
    getContractFactory(
      name: "IERC20Permit",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20Permit__factory>;
    getContractFactory(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20__factory>;
    getContractFactory(
      name: "AccessControl",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.AccessControl__factory>;
    getContractFactory(
      name: "IAccessControl",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IAccessControl__factory>;
    getContractFactory(
      name: "Ownable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Ownable__factory>;
    getContractFactory(
      name: "IERC1155Errors",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC1155Errors__factory>;
    getContractFactory(
      name: "IERC20Errors",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20Errors__factory>;
    getContractFactory(
      name: "IERC721Errors",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC721Errors__factory>;
    getContractFactory(
      name: "ERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC20__factory>;
    getContractFactory(
      name: "IERC20Metadata",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20Metadata__factory>;
    getContractFactory(
      name: "IERC20Permit",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20Permit__factory>;
    getContractFactory(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20__factory>;
    getContractFactory(
      name: "ERC721",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC721__factory>;
    getContractFactory(
      name: "IERC721Metadata",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC721Metadata__factory>;
    getContractFactory(
      name: "IERC721",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC721__factory>;
    getContractFactory(
      name: "IERC721Receiver",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC721Receiver__factory>;
    getContractFactory(
      name: "MerkleProof",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MerkleProof__factory>;
    getContractFactory(
      name: "ERC165",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC165__factory>;
    getContractFactory(
      name: "IERC165",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC165__factory>;
    getContractFactory(
      name: "Math",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Math__factory>;
    getContractFactory(
      name: "Strings",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Strings__factory>;
    getContractFactory(
      name: "DappadPaymasterDefault",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.DappadPaymasterDefault__factory>;
    getContractFactory(
      name: "DappadPaymasterGasless",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.DappadPaymasterGasless__factory>;
    getContractFactory(
      name: "DappadSale",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.DappadSale__factory>;
    getContractFactory(
      name: "DappadSaleFactory",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.DappadSaleFactory__factory>;
    getContractFactory(
      name: "DappadStake",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.DappadStake__factory>;
    getContractFactory(
      name: "DappadStakeController",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.DappadStakeController__factory>;
    getContractFactory(
      name: "DappadStakeControllerFactory",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.DappadStakeControllerFactory__factory>;
    getContractFactory(
      name: "DappadStakeFactory",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.DappadStakeFactory__factory>;
    getContractFactory(
      name: "DappadVesting",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.DappadVesting__factory>;
    getContractFactory(
      name: "DappadVestingFactory",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.DappadVestingFactory__factory>;
    getContractFactory(
      name: "Errors",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Errors__factory>;
    getContractFactory(
      name: "IDappadSale",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IDappadSale__factory>;
    getContractFactory(
      name: "IDappadStake",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IDappadStake__factory>;
    getContractFactory(
      name: "IDappadStakeController",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IDappadStakeController__factory>;
    getContractFactory(
      name: "IDappadVesting",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IDappadVesting__factory>;
    getContractFactory(
      name: "IERC20Extented",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20Extented__factory>;
    getContractFactory(
      name: "IERC721Extented",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC721Extented__factory>;
    getContractFactory(
      name: "Airdrop",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Airdrop__factory>;
    getContractFactory(
      name: "AirdropB",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.AirdropB__factory>;
    getContractFactory(
      name: "DappadSoulBoundToken",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.DappadSoulBoundToken__factory>;
    getContractFactory(
      name: "DappadToken",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.DappadToken__factory>;
    getContractFactory(
      name: "Faucet",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Faucet__factory>;
    getContractFactory(
      name: "IZkPassProofVerifier",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IZkPassProofVerifier__factory>;
    getContractFactory(
      name: "MockNFT",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MockNFT__factory>;
    getContractFactory(
      name: "MockToken",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MockToken__factory>;
    getContractFactory(
      name: "MockToken6",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MockToken6__factory>;
    getContractFactory(
      name: "ZkPassProofVerifier",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ZkPassProofVerifier__factory>;
    getContractFactory(
      name: "DappadNodeSale",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.DappadNodeSale__factory>;
    getContractFactory(
      name: "DappadNodeSaleFactory",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.DappadNodeSaleFactory__factory>;
    getContractFactory(
      name: "IDappadStakeController",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IDappadStakeController__factory>;
    getContractFactory(
      name: "IERC20Extented",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20Extented__factory>;
    getContractFactory(
      name: "IERC721Extented",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC721Extented__factory>;
    getContractFactory(
      name: "DappadSaleFactoryONFTHolders",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.DappadSaleFactoryONFTHolders__factory>;
    getContractFactory(
      name: "DappadSaleONFTHolders",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.DappadSaleONFTHolders__factory>;
    getContractFactory(
      name: "IDappadSale",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IDappadSale__factory>;
    getContractFactory(
      name: "IDappadStake",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IDappadStake__factory>;
    getContractFactory(
      name: "IDappadVesting",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IDappadVesting__factory>;
    getContractFactory(
      name: "IERC20Extented",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20Extented__factory>;
    getContractFactory(
      name: "IERC721Extented",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC721Extented__factory>;
    getContractFactory(
      name: "DappadVestingFactoryONFTHolders",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.DappadVestingFactoryONFTHolders__factory>;
    getContractFactory(
      name: "DappadVestingONFTHolders",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.DappadVestingONFTHolders__factory>;
    getContractFactory(
      name: "IDappadSale",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IDappadSale__factory>;
    getContractFactory(
      name: "IDappadStake",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IDappadStake__factory>;
    getContractFactory(
      name: "IDappadVesting",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IDappadVesting__factory>;
    getContractFactory(
      name: "IERC20Extented",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20Extented__factory>;
    getContractFactory(
      name: "IERC721Extented",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC721Extented__factory>;
    getContractFactory(
      name: "DappadSaleFactoryPrivateSale",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.DappadSaleFactoryPrivateSale__factory>;
    getContractFactory(
      name: "DappadSalePrivateSale",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.DappadSalePrivateSale__factory>;
    getContractFactory(
      name: "IDappadSale",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IDappadSale__factory>;
    getContractFactory(
      name: "IDappadStake",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IDappadStake__factory>;
    getContractFactory(
      name: "IDappadVesting",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IDappadVesting__factory>;
    getContractFactory(
      name: "IERC20Extented",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20Extented__factory>;
    getContractFactory(
      name: "IERC721Extented",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC721Extented__factory>;
    getContractFactory(
      name: "DappadPublicSale",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.DappadPublicSale__factory>;
    getContractFactory(
      name: "DappadPublicSaleFactory",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.DappadPublicSaleFactory__factory>;
    getContractFactory(
      name: "IDappadSale",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IDappadSale__factory>;
    getContractFactory(
      name: "IDappadStake",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IDappadStake__factory>;
    getContractFactory(
      name: "IDappadVesting",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IDappadVesting__factory>;
    getContractFactory(
      name: "IERC20Extented",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20Extented__factory>;
    getContractFactory(
      name: "IERC721Extented",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC721Extented__factory>;

    getContractAt(
      name: "BootloaderUtilities",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.BootloaderUtilities>;
    getContractAt(
      name: "IAccountCodeStorage",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IAccountCodeStorage>;
    getContractAt(
      name: "IBootloaderUtilities",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IBootloaderUtilities>;
    getContractAt(
      name: "IBytecodeCompressor",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IBytecodeCompressor>;
    getContractAt(
      name: "IContractDeployer",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IContractDeployer>;
    getContractAt(
      name: "IEthToken",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IEthToken>;
    getContractAt(
      name: "IImmutableSimulator",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IImmutableSimulator>;
    getContractAt(
      name: "IKnownCodesStorage",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IKnownCodesStorage>;
    getContractAt(
      name: "IL1Messenger",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IL1Messenger>;
    getContractAt(
      name: "INonceHolder",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.INonceHolder>;
    getContractAt(
      name: "IPaymaster",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IPaymaster>;
    getContractAt(
      name: "IPaymasterFlow",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IPaymasterFlow>;
    getContractAt(
      name: "ISystemContext",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ISystemContext>;
    getContractAt(
      name: "IERC20Permit",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20Permit>;
    getContractAt(
      name: "IERC20",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20>;
    getContractAt(
      name: "AccessControl",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.AccessControl>;
    getContractAt(
      name: "IAccessControl",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IAccessControl>;
    getContractAt(
      name: "Ownable",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Ownable>;
    getContractAt(
      name: "IERC1155Errors",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC1155Errors>;
    getContractAt(
      name: "IERC20Errors",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20Errors>;
    getContractAt(
      name: "IERC721Errors",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC721Errors>;
    getContractAt(
      name: "ERC20",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC20>;
    getContractAt(
      name: "IERC20Metadata",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20Metadata>;
    getContractAt(
      name: "IERC20Permit",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20Permit>;
    getContractAt(
      name: "IERC20",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20>;
    getContractAt(
      name: "ERC721",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC721>;
    getContractAt(
      name: "IERC721Metadata",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC721Metadata>;
    getContractAt(
      name: "IERC721",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC721>;
    getContractAt(
      name: "IERC721Receiver",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC721Receiver>;
    getContractAt(
      name: "MerkleProof",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MerkleProof>;
    getContractAt(
      name: "ERC165",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC165>;
    getContractAt(
      name: "IERC165",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC165>;
    getContractAt(
      name: "Math",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Math>;
    getContractAt(
      name: "Strings",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Strings>;
    getContractAt(
      name: "DappadPaymasterDefault",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.DappadPaymasterDefault>;
    getContractAt(
      name: "DappadPaymasterGasless",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.DappadPaymasterGasless>;
    getContractAt(
      name: "DappadSale",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.DappadSale>;
    getContractAt(
      name: "DappadSaleFactory",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.DappadSaleFactory>;
    getContractAt(
      name: "DappadStake",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.DappadStake>;
    getContractAt(
      name: "DappadStakeController",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.DappadStakeController>;
    getContractAt(
      name: "DappadStakeControllerFactory",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.DappadStakeControllerFactory>;
    getContractAt(
      name: "DappadStakeFactory",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.DappadStakeFactory>;
    getContractAt(
      name: "DappadVesting",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.DappadVesting>;
    getContractAt(
      name: "DappadVestingFactory",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.DappadVestingFactory>;
    getContractAt(
      name: "Errors",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Errors>;
    getContractAt(
      name: "IDappadSale",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IDappadSale>;
    getContractAt(
      name: "IDappadStake",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IDappadStake>;
    getContractAt(
      name: "IDappadStakeController",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IDappadStakeController>;
    getContractAt(
      name: "IDappadVesting",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IDappadVesting>;
    getContractAt(
      name: "IERC20Extented",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20Extented>;
    getContractAt(
      name: "IERC721Extented",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC721Extented>;
    getContractAt(
      name: "Airdrop",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Airdrop>;
    getContractAt(
      name: "AirdropB",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.AirdropB>;
    getContractAt(
      name: "DappadSoulBoundToken",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.DappadSoulBoundToken>;
    getContractAt(
      name: "DappadToken",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.DappadToken>;
    getContractAt(
      name: "Faucet",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Faucet>;
    getContractAt(
      name: "IZkPassProofVerifier",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IZkPassProofVerifier>;
    getContractAt(
      name: "MockNFT",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MockNFT>;
    getContractAt(
      name: "MockToken",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MockToken>;
    getContractAt(
      name: "MockToken6",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MockToken6>;
    getContractAt(
      name: "ZkPassProofVerifier",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ZkPassProofVerifier>;
    getContractAt(
      name: "DappadNodeSale",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.DappadNodeSale>;
    getContractAt(
      name: "DappadNodeSaleFactory",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.DappadNodeSaleFactory>;
    getContractAt(
      name: "IDappadStakeController",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IDappadStakeController>;
    getContractAt(
      name: "IERC20Extented",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20Extented>;
    getContractAt(
      name: "IERC721Extented",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC721Extented>;
    getContractAt(
      name: "DappadSaleFactoryONFTHolders",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.DappadSaleFactoryONFTHolders>;
    getContractAt(
      name: "DappadSaleONFTHolders",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.DappadSaleONFTHolders>;
    getContractAt(
      name: "IDappadSale",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IDappadSale>;
    getContractAt(
      name: "IDappadStake",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IDappadStake>;
    getContractAt(
      name: "IDappadVesting",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IDappadVesting>;
    getContractAt(
      name: "IERC20Extented",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20Extented>;
    getContractAt(
      name: "IERC721Extented",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC721Extented>;
    getContractAt(
      name: "DappadVestingFactoryONFTHolders",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.DappadVestingFactoryONFTHolders>;
    getContractAt(
      name: "DappadVestingONFTHolders",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.DappadVestingONFTHolders>;
    getContractAt(
      name: "IDappadSale",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IDappadSale>;
    getContractAt(
      name: "IDappadStake",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IDappadStake>;
    getContractAt(
      name: "IDappadVesting",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IDappadVesting>;
    getContractAt(
      name: "IERC20Extented",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20Extented>;
    getContractAt(
      name: "IERC721Extented",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC721Extented>;
    getContractAt(
      name: "DappadSaleFactoryPrivateSale",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.DappadSaleFactoryPrivateSale>;
    getContractAt(
      name: "DappadSalePrivateSale",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.DappadSalePrivateSale>;
    getContractAt(
      name: "IDappadSale",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IDappadSale>;
    getContractAt(
      name: "IDappadStake",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IDappadStake>;
    getContractAt(
      name: "IDappadVesting",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IDappadVesting>;
    getContractAt(
      name: "IERC20Extented",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20Extented>;
    getContractAt(
      name: "IERC721Extented",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC721Extented>;
    getContractAt(
      name: "DappadPublicSale",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.DappadPublicSale>;
    getContractAt(
      name: "DappadPublicSaleFactory",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.DappadPublicSaleFactory>;
    getContractAt(
      name: "IDappadSale",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IDappadSale>;
    getContractAt(
      name: "IDappadStake",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IDappadStake>;
    getContractAt(
      name: "IDappadVesting",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IDappadVesting>;
    getContractAt(
      name: "IERC20Extented",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20Extented>;
    getContractAt(
      name: "IERC721Extented",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC721Extented>;

    deployContract(
      name: "BootloaderUtilities",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.BootloaderUtilities>;
    deployContract(
      name: "IAccountCodeStorage",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IAccountCodeStorage>;
    deployContract(
      name: "IBootloaderUtilities",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IBootloaderUtilities>;
    deployContract(
      name: "IBytecodeCompressor",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IBytecodeCompressor>;
    deployContract(
      name: "IContractDeployer",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IContractDeployer>;
    deployContract(
      name: "IEthToken",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IEthToken>;
    deployContract(
      name: "IImmutableSimulator",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IImmutableSimulator>;
    deployContract(
      name: "IKnownCodesStorage",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IKnownCodesStorage>;
    deployContract(
      name: "IL1Messenger",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IL1Messenger>;
    deployContract(
      name: "INonceHolder",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.INonceHolder>;
    deployContract(
      name: "IPaymaster",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IPaymaster>;
    deployContract(
      name: "IPaymasterFlow",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IPaymasterFlow>;
    deployContract(
      name: "ISystemContext",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ISystemContext>;
    deployContract(
      name: "IERC20Permit",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20Permit>;
    deployContract(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20>;
    deployContract(
      name: "AccessControl",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.AccessControl>;
    deployContract(
      name: "IAccessControl",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IAccessControl>;
    deployContract(
      name: "Ownable",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Ownable>;
    deployContract(
      name: "IERC1155Errors",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC1155Errors>;
    deployContract(
      name: "IERC20Errors",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20Errors>;
    deployContract(
      name: "IERC721Errors",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC721Errors>;
    deployContract(
      name: "ERC20",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ERC20>;
    deployContract(
      name: "IERC20Metadata",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20Metadata>;
    deployContract(
      name: "IERC20Permit",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20Permit>;
    deployContract(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20>;
    deployContract(
      name: "ERC721",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ERC721>;
    deployContract(
      name: "IERC721Metadata",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC721Metadata>;
    deployContract(
      name: "IERC721",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC721>;
    deployContract(
      name: "IERC721Receiver",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC721Receiver>;
    deployContract(
      name: "MerkleProof",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MerkleProof>;
    deployContract(
      name: "ERC165",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ERC165>;
    deployContract(
      name: "IERC165",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC165>;
    deployContract(
      name: "Math",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Math>;
    deployContract(
      name: "Strings",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Strings>;
    deployContract(
      name: "DappadPaymasterDefault",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.DappadPaymasterDefault>;
    deployContract(
      name: "DappadPaymasterGasless",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.DappadPaymasterGasless>;
    deployContract(
      name: "DappadSale",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.DappadSale>;
    deployContract(
      name: "DappadSaleFactory",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.DappadSaleFactory>;
    deployContract(
      name: "DappadStake",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.DappadStake>;
    deployContract(
      name: "DappadStakeController",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.DappadStakeController>;
    deployContract(
      name: "DappadStakeControllerFactory",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.DappadStakeControllerFactory>;
    deployContract(
      name: "DappadStakeFactory",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.DappadStakeFactory>;
    deployContract(
      name: "DappadVesting",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.DappadVesting>;
    deployContract(
      name: "DappadVestingFactory",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.DappadVestingFactory>;
    deployContract(
      name: "Errors",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Errors>;
    deployContract(
      name: "IDappadSale",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IDappadSale>;
    deployContract(
      name: "IDappadStake",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IDappadStake>;
    deployContract(
      name: "IDappadStakeController",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IDappadStakeController>;
    deployContract(
      name: "IDappadVesting",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IDappadVesting>;
    deployContract(
      name: "IERC20Extented",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20Extented>;
    deployContract(
      name: "IERC721Extented",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC721Extented>;
    deployContract(
      name: "Airdrop",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Airdrop>;
    deployContract(
      name: "AirdropB",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.AirdropB>;
    deployContract(
      name: "DappadSoulBoundToken",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.DappadSoulBoundToken>;
    deployContract(
      name: "DappadToken",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.DappadToken>;
    deployContract(
      name: "Faucet",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Faucet>;
    deployContract(
      name: "IZkPassProofVerifier",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IZkPassProofVerifier>;
    deployContract(
      name: "MockNFT",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockNFT>;
    deployContract(
      name: "MockToken",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockToken>;
    deployContract(
      name: "MockToken6",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockToken6>;
    deployContract(
      name: "ZkPassProofVerifier",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ZkPassProofVerifier>;
    deployContract(
      name: "DappadNodeSale",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.DappadNodeSale>;
    deployContract(
      name: "DappadNodeSaleFactory",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.DappadNodeSaleFactory>;
    deployContract(
      name: "IDappadStakeController",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IDappadStakeController>;
    deployContract(
      name: "IERC20Extented",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20Extented>;
    deployContract(
      name: "IERC721Extented",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC721Extented>;
    deployContract(
      name: "DappadSaleFactoryONFTHolders",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.DappadSaleFactoryONFTHolders>;
    deployContract(
      name: "DappadSaleONFTHolders",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.DappadSaleONFTHolders>;
    deployContract(
      name: "IDappadSale",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IDappadSale>;
    deployContract(
      name: "IDappadStake",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IDappadStake>;
    deployContract(
      name: "IDappadVesting",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IDappadVesting>;
    deployContract(
      name: "IERC20Extented",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20Extented>;
    deployContract(
      name: "IERC721Extented",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC721Extented>;
    deployContract(
      name: "DappadVestingFactoryONFTHolders",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.DappadVestingFactoryONFTHolders>;
    deployContract(
      name: "DappadVestingONFTHolders",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.DappadVestingONFTHolders>;
    deployContract(
      name: "IDappadSale",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IDappadSale>;
    deployContract(
      name: "IDappadStake",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IDappadStake>;
    deployContract(
      name: "IDappadVesting",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IDappadVesting>;
    deployContract(
      name: "IERC20Extented",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20Extented>;
    deployContract(
      name: "IERC721Extented",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC721Extented>;
    deployContract(
      name: "DappadSaleFactoryPrivateSale",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.DappadSaleFactoryPrivateSale>;
    deployContract(
      name: "DappadSalePrivateSale",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.DappadSalePrivateSale>;
    deployContract(
      name: "IDappadSale",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IDappadSale>;
    deployContract(
      name: "IDappadStake",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IDappadStake>;
    deployContract(
      name: "IDappadVesting",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IDappadVesting>;
    deployContract(
      name: "IERC20Extented",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20Extented>;
    deployContract(
      name: "IERC721Extented",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC721Extented>;
    deployContract(
      name: "DappadPublicSale",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.DappadPublicSale>;
    deployContract(
      name: "DappadPublicSaleFactory",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.DappadPublicSaleFactory>;
    deployContract(
      name: "IDappadSale",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IDappadSale>;
    deployContract(
      name: "IDappadStake",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IDappadStake>;
    deployContract(
      name: "IDappadVesting",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IDappadVesting>;
    deployContract(
      name: "IERC20Extented",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20Extented>;
    deployContract(
      name: "IERC721Extented",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC721Extented>;

    deployContract(
      name: "BootloaderUtilities",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.BootloaderUtilities>;
    deployContract(
      name: "IAccountCodeStorage",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IAccountCodeStorage>;
    deployContract(
      name: "IBootloaderUtilities",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IBootloaderUtilities>;
    deployContract(
      name: "IBytecodeCompressor",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IBytecodeCompressor>;
    deployContract(
      name: "IContractDeployer",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IContractDeployer>;
    deployContract(
      name: "IEthToken",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IEthToken>;
    deployContract(
      name: "IImmutableSimulator",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IImmutableSimulator>;
    deployContract(
      name: "IKnownCodesStorage",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IKnownCodesStorage>;
    deployContract(
      name: "IL1Messenger",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IL1Messenger>;
    deployContract(
      name: "INonceHolder",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.INonceHolder>;
    deployContract(
      name: "IPaymaster",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IPaymaster>;
    deployContract(
      name: "IPaymasterFlow",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IPaymasterFlow>;
    deployContract(
      name: "ISystemContext",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ISystemContext>;
    deployContract(
      name: "IERC20Permit",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20Permit>;
    deployContract(
      name: "IERC20",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20>;
    deployContract(
      name: "AccessControl",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.AccessControl>;
    deployContract(
      name: "IAccessControl",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IAccessControl>;
    deployContract(
      name: "Ownable",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Ownable>;
    deployContract(
      name: "IERC1155Errors",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC1155Errors>;
    deployContract(
      name: "IERC20Errors",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20Errors>;
    deployContract(
      name: "IERC721Errors",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC721Errors>;
    deployContract(
      name: "ERC20",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ERC20>;
    deployContract(
      name: "IERC20Metadata",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20Metadata>;
    deployContract(
      name: "IERC20Permit",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20Permit>;
    deployContract(
      name: "IERC20",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20>;
    deployContract(
      name: "ERC721",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ERC721>;
    deployContract(
      name: "IERC721Metadata",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC721Metadata>;
    deployContract(
      name: "IERC721",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC721>;
    deployContract(
      name: "IERC721Receiver",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC721Receiver>;
    deployContract(
      name: "MerkleProof",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MerkleProof>;
    deployContract(
      name: "ERC165",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ERC165>;
    deployContract(
      name: "IERC165",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC165>;
    deployContract(
      name: "Math",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Math>;
    deployContract(
      name: "Strings",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Strings>;
    deployContract(
      name: "DappadPaymasterDefault",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.DappadPaymasterDefault>;
    deployContract(
      name: "DappadPaymasterGasless",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.DappadPaymasterGasless>;
    deployContract(
      name: "DappadSale",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.DappadSale>;
    deployContract(
      name: "DappadSaleFactory",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.DappadSaleFactory>;
    deployContract(
      name: "DappadStake",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.DappadStake>;
    deployContract(
      name: "DappadStakeController",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.DappadStakeController>;
    deployContract(
      name: "DappadStakeControllerFactory",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.DappadStakeControllerFactory>;
    deployContract(
      name: "DappadStakeFactory",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.DappadStakeFactory>;
    deployContract(
      name: "DappadVesting",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.DappadVesting>;
    deployContract(
      name: "DappadVestingFactory",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.DappadVestingFactory>;
    deployContract(
      name: "Errors",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Errors>;
    deployContract(
      name: "IDappadSale",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IDappadSale>;
    deployContract(
      name: "IDappadStake",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IDappadStake>;
    deployContract(
      name: "IDappadStakeController",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IDappadStakeController>;
    deployContract(
      name: "IDappadVesting",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IDappadVesting>;
    deployContract(
      name: "IERC20Extented",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20Extented>;
    deployContract(
      name: "IERC721Extented",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC721Extented>;
    deployContract(
      name: "Airdrop",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Airdrop>;
    deployContract(
      name: "AirdropB",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.AirdropB>;
    deployContract(
      name: "DappadSoulBoundToken",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.DappadSoulBoundToken>;
    deployContract(
      name: "DappadToken",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.DappadToken>;
    deployContract(
      name: "Faucet",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Faucet>;
    deployContract(
      name: "IZkPassProofVerifier",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IZkPassProofVerifier>;
    deployContract(
      name: "MockNFT",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockNFT>;
    deployContract(
      name: "MockToken",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockToken>;
    deployContract(
      name: "MockToken6",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockToken6>;
    deployContract(
      name: "ZkPassProofVerifier",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ZkPassProofVerifier>;
    deployContract(
      name: "DappadNodeSale",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.DappadNodeSale>;
    deployContract(
      name: "DappadNodeSaleFactory",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.DappadNodeSaleFactory>;
    deployContract(
      name: "IDappadStakeController",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IDappadStakeController>;
    deployContract(
      name: "IERC20Extented",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20Extented>;
    deployContract(
      name: "IERC721Extented",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC721Extented>;
    deployContract(
      name: "DappadSaleFactoryONFTHolders",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.DappadSaleFactoryONFTHolders>;
    deployContract(
      name: "DappadSaleONFTHolders",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.DappadSaleONFTHolders>;
    deployContract(
      name: "IDappadSale",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IDappadSale>;
    deployContract(
      name: "IDappadStake",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IDappadStake>;
    deployContract(
      name: "IDappadVesting",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IDappadVesting>;
    deployContract(
      name: "IERC20Extented",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20Extented>;
    deployContract(
      name: "IERC721Extented",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC721Extented>;
    deployContract(
      name: "DappadVestingFactoryONFTHolders",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.DappadVestingFactoryONFTHolders>;
    deployContract(
      name: "DappadVestingONFTHolders",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.DappadVestingONFTHolders>;
    deployContract(
      name: "IDappadSale",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IDappadSale>;
    deployContract(
      name: "IDappadStake",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IDappadStake>;
    deployContract(
      name: "IDappadVesting",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IDappadVesting>;
    deployContract(
      name: "IERC20Extented",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20Extented>;
    deployContract(
      name: "IERC721Extented",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC721Extented>;
    deployContract(
      name: "DappadSaleFactoryPrivateSale",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.DappadSaleFactoryPrivateSale>;
    deployContract(
      name: "DappadSalePrivateSale",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.DappadSalePrivateSale>;
    deployContract(
      name: "IDappadSale",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IDappadSale>;
    deployContract(
      name: "IDappadStake",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IDappadStake>;
    deployContract(
      name: "IDappadVesting",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IDappadVesting>;
    deployContract(
      name: "IERC20Extented",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20Extented>;
    deployContract(
      name: "IERC721Extented",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC721Extented>;
    deployContract(
      name: "DappadPublicSale",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.DappadPublicSale>;
    deployContract(
      name: "DappadPublicSaleFactory",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.DappadPublicSaleFactory>;
    deployContract(
      name: "IDappadSale",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IDappadSale>;
    deployContract(
      name: "IDappadStake",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IDappadStake>;
    deployContract(
      name: "IDappadVesting",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IDappadVesting>;
    deployContract(
      name: "IERC20Extented",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20Extented>;
    deployContract(
      name: "IERC721Extented",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC721Extented>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
